package org.estatio.dscm.dom.playlist;

public enum PlaylistRepeat {

    DAILY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR,SA,SU"),
    EVERY_WEEKDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR"),
    EVERY_WEEKEND("RRULE:FREQ=DAILY;BYDAY=SA,SU"),

    MONDAY("RRULE:FREQ=DAILY;BYDAY=MO"),
    MONDAY_TUESDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU"),
    MONDAY_TUESDAY_WEDNESDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE"),
    MONDAY_TUESDAY_WEDNESDAY_THURSDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH"),
    MONDAY_TUESDAY_WEDNESDAY_THURSDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,SA"),
    MONDAY_TUESDAY_WEDNESDAY_THURSDAY_FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR,SU"),
    MONDAY_TUESDAY_WEDNESDAY_THURSDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,SA"),
    MONDAY_TUESDAY_WEDNESDAY_THURSDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,SA,SU"),
    MONDAY_TUESDAY_WEDNESDAY_THURSDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,SU"),
    MONDAY_TUESDAY_WEDNESDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,FR"),
    MONDAY_TUESDAY_WEDNESDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,FR,SA"),
    MONDAY_TUESDAY_WEDNESDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,FR,SA,SU"),
    MONDAY_TUESDAY_WEDNESDAY_FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,FR,SU"),
    MONDAY_TUESDAY_WEDNESDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,SA"),
    MONDAY_TUESDAY_WEDNESDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,SA,SU"),
    MONDAY_TUESDAY_WEDNESDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,SU"),
    MONDAY_TUESDAY_THURSDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,TH"),
    MONDAY_TUESDAY_THURSDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,TH,FR"),
    MONDAY_TUESDAY_THURSDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,TH,FR,SA"),
    MONDAY_TUESDAY_THURSDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,TH,FR,SA,SU"),
    MONDAY_TUESDAY_THURSDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,TH,SA"),
    MONDAY_TUESDAY_THURSDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,TH,SA,SU"),
    MONDAY_TUESDAY_THURSDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,TH,SU"),
    MONDAY_TUESDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,FR"),
    MONDAY_TUESDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,FR,SA"),
    MONDAY_TUESDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,FR,SA,SU"),
    MONDAY_TUESDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,SA"),
    MONDAY_TUESDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,SA,SU"),
    MONDAY_TUESDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TU,SU"),
    MONDAY_WEDNESDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE"),
    MONDAY_WEDNESDAY_THURSDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,TH"),
    MONDAY_WEDNESDAY_THURSDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,TH,FR"),
    MONDAY_WEDNESDAY_THURSDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,TH,FR,SA"),
    MONDAY_WEDNESDAY_THURSDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,TH,FR,SA,SU"),
    MONDAY_WEDNESDAY_THURSDAY_FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,TH,FR,SU"),
    MONDAY_WEDNESDAY_THURSDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,TH,SA"),
    MONDAY_WEDNESDAY_THURSDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,TH,SA,SU"),
    MONDAY_WEDNESDAY_THURSDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,TH,SU"),
    MONDAY_WEDNESDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,FR"),
    MONDAY_WEDNESDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,FR,SA"),
    MONDAY_WEDNESDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,FR,SA,SU"),
    MONDAY_WEDNESDAY_FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,FR,SU"),
    MONDAY_WEDNESDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,SA"),
    MONDAY_WEDNESDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,SA,SU"),
    MONDAY_WEDNESDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,WE,SU"),
    MONDAY_THURSDAY("RRULE:FREQ=DAILY;BYDAY=MO,TH"),
    MONDAY_THURSDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=MO,TH,FR"),
    MONDAY_THURSDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,TH,FR,SA"),
    MONDAY_THURSDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TH,FR,SA,SU"),
    MONDAY_THURSDAY_FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TH,FR,SU"),
    MONDAY_THURSDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,TH,SA"),
    MONDAY_THURSDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TH,SA,SU"),
    MONDAY_THURSDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,TH,SU"),
    MONDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=MO,FR"),
    MONDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,FR,SA"),
    MONDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,FR,SA,SU"),
    MONDAY_FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,FR,SU"),
    MONDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=MO,SA"),
    MONDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,SA,SU"),
    MONDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=MO,SU"),

    TUESDAY("RRULE:FREQ=DAILY;BYDAY=TU"),
    TUESDAY_WEDNESDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE"),
    TUESDAY_WEDNESDAY_THURSDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,TH"),
    TUESDAY_WEDNESDAY_THURSDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,TH,FR"),
    TUESDAY_WEDNESDAY_THURSDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,TH,FR,SA"),
    TUESDAY_WEDNESDAY_THURSDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,TH,FR,SA,SU"),
    TUESDAY_WEDNESDAY_THURSDAY_FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,TH,FR,SU"),
    TUESDAY_WEDNESDAY_THURSDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,TH,SA"),
    TUESDAY_WEDNESDAY_THURSDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,TH,SA,SU"),
    TUESDAY_WEDNESDAY_THURSDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,TH,SU"),
    TUESDAY_WEDNESDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,FR"),
    TUESDAY_WEDNESDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,FR,SA"),
    TUESDAY_WEDNESDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,FR,SA,SU"),
    TUESDAY_WEDNESDAY_FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,FR,SU"),
    TUESDAY_WEDNESDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,SA"),
    TUESDAY_WEDNESDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,SA,SU"),
    TUESDAY_WEDNESDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,WE,SU"),
    TUESDAY_THURSDAY("RRULE:FREQ=WEEKLY;BYDAY=TU,TH"),
    TUESDAY_THURSDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=TU,TH,FR"),
    TUESDAY_THURSDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=TU,TH,FR,SA"),
    TUESDAY_THURSDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,TH,FR,SA,SU"),
    TUESDAY_THURSDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=TU,TH,SA"),
    TUESDAY_THURSDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,TH,SA,SU"),
    TUESDAY_THURSDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,TH,SU"),
    TUESDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=TU,FR"),
    TUESDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=TU,FR,SA"),
    TUESDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,FR,SA,SU"),
    TUESDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=TU,SA"),
    TUESDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,SA,SU"),
    TUESDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TU,SU"),

    WEDNESDAY("RRULE:FREQ=DAILY;BYDAY=WE"),
    WEDNESDAY_THURSDAY("RRULE:FREQ=DAILY;BYDAY=WE,TH"),
    WEDNESDAY_THURSDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=WE,TH,FR"),
    WEDNESDAY_THURSDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=WE,TH,FR,SA"),
    WEDNESDAY_THURSDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=WE,TH,FR,SA,SU"),
    WEDNESDAY_THURSDAY_FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=WE,TH,FR,SU"),
    WEDNESDAY_THURSDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=WE,TH,SA"),
    WEDNESDAY_THURSDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=WE,TH,SA,SU"),
    WEDNESDAY_THURSDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=WE,TH,SU"),
    WEDNESDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=WE,FR"),
    WEDNESDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=WE,FR,SA"),
    WEDNESDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=WE,FR,SA,SU"),
    WEDNESDAY_FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=WE,FR,SU"),
    WEDNESDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=WE,SA"),
    WEDNESDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=WE,SA,SU"),
    WEDNESDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=WE,SU"),

    THURSDAY("RRULE:FREQ=DAILY;BYDAY=TH"),
    THURSDAY_FRIDAY("RRULE:FREQ=DAILY;BYDAY=TH,FR"),
    THURSDAY_FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=TH,FR,SA"),
    THURSDAY_FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TH,FR,SA,SU"),
    THURSDAY_FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TH,FR,SU"),
    THURSDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=TH,SA"),
    THURSDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TH,SA,SU"),
    THURSDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=TH,SU"),

    FRIDAY("RRULE:FREQ=DAILY;BYDAY=FR"),
    FRIDAY_SATURDAY("RRULE:FREQ=DAILY;BYDAY=FR,SA"),
    FRIDAY_SATURDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=FR,SA,SU"),
    FRIDAY_SUNDAY("RRULE:FREQ=DAILY;BYDAY=FR,SU"),

    SATURDAY("RRULE:FREQ=DAILY;BYDAY=SA"),

    SUNDAY("RRULE:FREQ=DAILY;BYDAY=SU");

    private String rrule;

    private PlaylistRepeat(String rrule) {
        this.rrule = rrule;
    }

    public String rrule() {
        return rrule;
    }

    public String title() {
        return this.name();
    }

    public static PlaylistRepeat stringToPlaylistRepeat(String rule) {
        for (PlaylistRepeat e : PlaylistRepeat.values()) {
            if (rule.equals(e.rrule())) {
                return e;
            }
        }

        return null;
    }

    public static boolean[] playlistRepeatToBooleans(String rule) {
        boolean[] days = new boolean[7];
        String[] splitDays = rule.split("=")[2].split(",");

        for (String eachDay : splitDays) {
            switch (eachDay) {
                case "MO":
                    days[0] = true;
                    break;
                case "TU":
                    days[1] = true;
                    break;
                case "WE":
                    days[2] = true;
                    break;
                case "TH":
                    days[3] = true;
                    break;
                case "FR":
                    days[4] = true;
                    break;
                case "SA":
                    days[5] = true;
                    break;
                case "SU":
                    days[6] = true;
                    break;
            }
        }

        return days;
    }
}
